package edu.colorado.csdms.wmt.client.ui;

import com.google.gwt.dom.client.Style.Cursor;
import com.google.gwt.dom.client.Style.Unit;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.user.client.ui.Grid;
import com.google.gwt.user.client.ui.HTML;

import edu.colorado.csdms.wmt.client.control.DataManager;
import edu.colorado.csdms.wmt.client.control.DataTransfer;
import edu.colorado.csdms.wmt.client.control.DataURL;

/**
 * Supplies a Grid with links for viewing or downloading the input
 * configuration files generated by the parameters set for a component in a
 * model.
 * 
 * @author Mark Piper (mark.piper@colorado.edu)
 */
public class ViewInputFilesPanel extends Grid {

  private DataManager data;
  private String componentId;

  /**
   * Creates a new ViewInputFilesPanel with links built for the current state
   * of a model component parameter.
   * 
   * @param data the DataManager object for the WMT session
   * @param componentId the id of the model component, a String
   */
  public ViewInputFilesPanel(DataManager data, String componentId) {

    super(1, 6);
    this.data = data;
    this.componentId = componentId;
    this.getElement().getStyle().setMarginTop(2, Unit.EM);
    this.setCellPadding(5); // px

    String formatUrl = DataURL.formatComponent(data, componentId);
    String urlHtml = formatUrl + "?format=html";
    String urlText = formatUrl + "?format=text";
    String urlJson = formatUrl + "?format=json";
    HTML viewHtml = new HTML("<a href='" + urlHtml + "'>HTML</a>");
    HTML viewText = new HTML("<a href='" + urlText + "'>text</a>");
    HTML viewJson = new HTML("<a href='" + urlJson + "'>JSON</a>");

    viewHtml.getElement().getStyle().setCursor(Cursor.POINTER);
    viewText.getElement().getStyle().setCursor(Cursor.POINTER);
    viewJson.getElement().getStyle().setCursor(Cursor.POINTER);

    HTML viewTitle = new HTML("View input files:");
    viewTitle.setTitle("View the model configuration files generated by "
        + "these parameter values");

    this.setWidget(0, 0, viewTitle);
    this.setWidget(0, 1, viewHtml);
    this.setWidget(0, 2, new HTML("|"));
    this.setWidget(0, 3, viewText);
    this.setWidget(0, 4, new HTML("|"));
    this.setWidget(0, 5, viewJson);

    viewHtml.addClickHandler(new InterceptClickHandler("html"));
    viewText.addClickHandler(new InterceptClickHandler("text"));
    viewJson.addClickHandler(new InterceptClickHandler("json"));
  }

  /**
   * Intercepts the click on the link in the HTML, text or JSON cell and
   * directs it to open in another tab/window.
   */
  public class InterceptClickHandler implements ClickHandler {

    private String type;

    public InterceptClickHandler(String type) {
      this.type = type;
    }

    @Override
    public void onClick(ClickEvent event) {
      event.preventDefault();
      DataTransfer.viewInputFiles(data, componentId, type);
    }
  }
}
